stages:
  - build
  - update-helm

variables:
  DOCKER_TLS_CERTDIR: ""
  FRONTEND_IMAGE: $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_SHORT_SHA
  BACKEND_IMAGE: $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_SHORT_SHA

.default-docker:
  image: docker:24
  services:
    - docker:24-dind
  before_script:
    # Login to GitLab Container Registry
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    # Enable Buildx for cross-platform builds
    - docker buildx create --use

# -------------------------
# BUILD FRONTEND (ARM64)
# -------------------------
build-frontend:
  stage: build
  extends: .default-docker
  script:
    - docker buildx build --build-arg REACT_APP_API_URL=$REACT_APP_API_URL --platform linux/arm64 -t $FRONTEND_IMAGE ./app/frontend --push
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - app/frontend/**/*

# -------------------------
# BUILD BACKEND (ARM64)
# -------------------------
build-backend:
  stage: build
  extends: .default-docker
  script:
    - docker buildx build --platform linux/arm64 -t $BACKEND_IMAGE ./app/backend --push
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - app/backend/**/*

# -------------------------
# UPDATE HELM VALUES (FRONTEND)
# -------------------------
update-helm-frontend:
  stage: update-helm
  image: bitnami/git:latest
  script:
    - git config --global user.email "ci-bot@example.com"
    - git config --global user.name "CI Bot"
    - git remote set-url origin https://$CI_USERNAME:$CI_PASSWORD@gitlab.com/deeowemez/task-app.git
    - git checkout main
    - echo "Updating frontend image in Helm values.yaml"
    - sed -i "s|^\(\s*fe_tag:\s*\).*|\1$CI_COMMIT_SHORT_SHA|" app/helm/values.yaml
    - git add app/helm/values.yaml
    - git commit -m "Update frontend image"
    - git push origin main
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - app/frontend/**/*

# -------------------------
# UPDATE HELM VALUES (BACKEND)
# -------------------------
update-helm-backend:
  stage: update-helm
  image: bitnami/git:latest
  script:
    - git config --global user.email "ci-bot@example.com"
    - git config --global user.name "CI Bot"
    - git remote set-url origin https://$CI_USERNAME:$CI_PASSWORD@gitlab.com/deeowemez/task-app.git
    - git checkout main
    - echo "Updating backend image in Helm values.yaml"
    - sed -i "s|^\(\s*be_tag:\s*\).*|\1$CI_COMMIT_SHORT_SHA|" app/helm/values.yaml
    - git add app/helm/values.yaml
    - git commit -m "Update backend image"
    - git push origin main
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - app/backend/**/*