stages:
  - build

variables:
  # Required for Docker-in-Docker to work properly
  DOCKER_TLS_CERTDIR: ""

  FRONTEND_IMAGE: $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_SHORT_SHA
  BACKEND_IMAGE: $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_SHORT_SHA

.default-docker:
  image: docker:24
  services:
    - docker:24-dind
  before_script:
    # Login to GitLab Container Registry
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

# -------------------------
# BUILD FRONTEND
# -------------------------
build-frontend:
  stage: build
  extends: .default-docker
  script:
    - docker build -t $FRONTEND_IMAGE ./app/frontend
    - docker push $FRONTEND_IMAGE
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - app/frontend/**/*


# -------------------------
# BUILD BACKEND
# -------------------------
build-backend:
  stage: build
  extends: .default-docker
  script:
    - docker build -t $BACKEND_IMAGE ./app/backend
    - docker push $BACKEND_IMAGE
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - app/backend/**/*