---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-registry-secret
  namespace: task-app
spec:
  encryptedData:
    .dockerconfigjson: AgC20R017NfIgBrjxFSZQgN+q7pzTMVh30lb/NJc1GhjxetGJmvX+Q5cZKOL3CvjkRLR6jxrOuImPF+s1rKpSBK0TxjnSZNwp4zD92hdbZf+uDXvts/4S+I6KDJdC2K3Ry0JE+AlAXGHfvN9BQz6hAhLZE+kJAJofaP9FNIhgXdiIzK5hMHxBws9z2sG+2aIs9uc/F1iBjObk5AxiAB1xekacl84BMKO02cDafvlFc5/y3p3AiBgFkq81rXUXC2wVv6YTDLwDoni9oKOmQ0ZfTk2Ds8cW7qeMDCA0/S6YRluTU6g9i9q53/9SZDYRYoaj/IYIF5fFqXkUeUjs8siqQ+uyms84kvdw4lYj5O0qZCBpEz7XQ/qrVIHLjp+R1rz1tRUj5ZzgJF6k854eEF0v8O/5EVKO12MfaAbvpXX07CM0fSJAcLZt0NNnKOwAmdQlxFwuXTs4Qok8BFFa8DwTtwnX7fVhlah4VLhSGgN//v+JTfpc379cZDfzkt47G4/H63x9haSbwHn31uPv15AUY6zgWzWOvx94tT5H6u2tDKq3Bwc0STjsKhd+GwSNpNU11wvWwratyOvUU5+uv1ISAZLGf2FUVLoY/tq8RsknINmkBrIAO9PvV3k0ep7Pam2FZVXs8uWLFdmp1d196A9W49BZsUdGbnM7u6bELezd6vtI9FJGMMDiLCaRMgrDfxMCDuzAbl8+VwNX/hGb/Y+n9RF7nyac0GJP1p+Dfgj6jk1nvz65fr5TAQ1hSAm282XbXq5hmjYnRsUObDVjI5a1I0BaYZYg4fnXoHtAtFw4A0Hw5SSDoWY+jFbwurvF8Dax0x1vVqFGy81VWIuTEo4qGpjGuNYB1zZoAnGI1N0gf0GNJyonV84pwjhrS0AH0FXhrQGGs4XJfJYntUhpGISYT9i9DOp3vE3nPYeCrmIHuRqDYUjsq6BlhDUrao56X11Jzg+X9dVh+C/SGCCjgtz3JVSeE2ezEO0WyESUc3GrAf1fCOFRu1JOfCZXVdFDkaU1EtLc6hUrKN5s2wHju2hjdka/d2J3RnYxCHcXAMi
  template:
    metadata:
      name: gitlab-registry-secret
      namespace: task-app
    type: kubernetes.io/dockerconfigjson
