---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: observability
spec:
  encryptedData:
    admin-password: AgA7s5mbid5oIzbi3T6DTKKKuXtoyxYZBl5haQ9LB7w+dH2q3mBBkt2LNex1hgh1s2W5pavhzp+t4XobFTnyyQh5t9MatvQ8VSXcyfje90ocXzcelJjsAX9velmFsAw1ey7HPnLS7QjXzDtCV+088w8eUuLy61rWIWEDZ7K/7vOU9/5nuAN0eKtHSSFSJR9w2RSAZXX0oSZh7SmcS8A7sDBH1i9voB3yZ64+hPe72P9IGJiujvRiCBAYC7lkvs4Y8WHmKr/ywOAHd7bcql0GtuGp8YIh/8B7gIuCsf2Gqq8HWiZSozXnLXH+tl/pTqtMqC8xCuL87mks97YGPjWnb5PrTSayObqA8FmBFmiy8f77m7vadGimwLhXehZ8Ku480FCnDahNo6botH9PCDJ/nF27uyXKF8W/Vuj6Zz5o5k4Z0Qfz+0QFUFj9zrTvCrGULNNdc8+qRp2JFAZUMxt2QMO6apj4SU4o5KUJzXwLxWM6SlOUNKAwnCw7v2bK4CNAADtGdFP85gBqXTDCCfc1tz/1aJ34Q4i2AwjXwyDhgePAkrpgiMtpqbhbE5PStJVMnWyhdA7oZuYBQQGy0+sUIviJdkzox2WCv77JGMydfFhmnDDugaclBpByJCNjZD7F9E+iMu9mihSgjAZpfuWp/Cj95z+iQr3lbGTNML/FRz3dDgch7NHb1sHYIOfmTSaMBu+liveKGrZJlg==
    admin-user: AgBXm70PaU4h3m3IGCk15NPItPlvIjroYWbrApGjzDucq7FG2fukxUSM9PiS+duOM+ha0c4xS4qIoIdsLT7k+g7GpMZacELcJbdDasHOrvRIXLbSOoi8JbBfmXue2vMmuAI8fFwflxeKksN/Dzv813Zl/nvFQpwjc7tJ0AHR8Nr00wLv9F64GgLxnb7lLQoTbaF5clwkDtclCM+d1cbTot/cC1dcRZYpivlDRNMdAlBBNBXyE1BemPcqvJU7kmp/3hM2qdHznefMLjhgC+5R0+q8Oc2CjkBQHAhbPFPUszTy/aZWj3H8gcyEIAt9PmVnnaeCFckGyaxtRl9k+q+awzfU/Gu+Xn1pkXfaSthhNSnnSIDxDarpoZDZ4bDeDujQ575LxfViAGgItIppYZ4M4s1XXKr83Rsdm78tFidv1IID7st69dW7jIK1Ov12hgamXRTCH4ULjGffZAI+7MeeYacOnzWNKklcUUVbCzjPKbrVrYs9oPOXimcTOSyzxXvp0SfK9FEELqq+ilYdhjPO0XLwsw/I7P3oNj3jSsZt8YnhVgj5SxSNXGKGX5H5aWZvPUFwLCQVCM25mumPFJvKX8LQwmuvMdLZ+X4eYJKaH8X+XRQ6fw5+3wQH7TsvCZkrlpv9C6mR1T8NVrnHV8F64XJIACaOdFqkU7/0jDNVCotWyAjmD2bEi+6ToE/ZQkxU3IqYakdBAg==
  template:
    metadata:
      name: grafana-admin
      namespace: observability
    type: Opaque
