# Release:    promtail
# Chart:      grafana/promtail
# Version:    6.17.1         # app version 3.5.1
# Namespace:  observability


config:
  clients:
  - url: http://loki.observability.svc.cluster.local:3100/loki/api/v1/push
