# Release:    tempo
# Chart:      grafana/tempo
# Version:    1.24.4         # app version 2.9.0
# Namespace:  observability

replicas: 0
resources:
  limits:
    memory: 256Mi
  requests:
    memory: 128Mi
tempo:
  retention: 24h
