{
 "title": "Task App Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "options": { "content": "# Task App Dashboard" } },
  { "title": "Overview Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Application Health Overview",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "up{job=\"backend\"}",
     "legendFormat": "Container: {{container}}"
    }
   ]
  },
  {
   "title": "Error Rate %",
   "type": "stat",
   "description": "Error rate percentage",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  sum(rate(http_requests_total{status_code=~\"5..\"}[5m]))\r\n  /\r\n  sum(rate(http_requests_total[5m]))\r\n) * 100",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "HTTP Requests per Second",
   "type": "timeseries",
   "description": "Request rate over 5 minutes",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "sum by (method, route, status_code) (\r\n  rate(http_requests_total[5m])\r\n)",
     "legendFormat": "{{method}} {{route}} {{status_code}}"
    }
   ]
  },
  { "title": "Application Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Average Response Time",
   "type": "timeseries",
   "description": " Average response time",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum[5m]) / rate(http_request_duration_seconds_count[5m])",
     "legendFormat": "{{method}} {{route}} {{status_code}}"
    }
   ]
  },
  { "title": "Infrastructure Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Pod CPU Usage",
   "type": "timeseries",
   "description": "Memory usage by pod",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (\r\n  container_memory_working_set_bytes{\r\n    pod=~\"task-app.*\",\r\n    container!=\"\",\r\n    image!=\"\"\r\n  }\r\n) / 1024 / 1024",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Logs Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Application Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{namespace=\"task-app\"}"
    }
   ]
  }
 ]
}