---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-registry-secret
  namespace: task-app
spec:
  encryptedData:
    .dockerconfigjson: AgBt1GYnVo+YbUhQXm4vV7pzlD6FlJEYxHoW9N7DBo84C1+9/JLu1L+gW/MM5rAcGTb/a8sC4KGsvVfjmQzFSP8T5PUf/rki7HzMlkHW+3YKJBwPVQ0a/RSHKJiWgH+CUJb4dJ8vKJObyM8Xe7dv0zlrrYVjeIT5KQcln3LDd7US2LmQoW9O55YqO9ClEOBM24hlfmAsl3Nt6diJXPPU5vEglrBhlrCtQ/qJzG+0yHl9pnb5wgQiBp+u/BMRSvHgu5QwJb6DE7dFbTKm6SgM1Z6BpD0pM7yoRvudiulcxtTVAYos+gtbKEQs7h60TIKzxGGhrDT4mmmQTawgQxphjnfEaLpxbL0BaK7CmNeST8OoYQHTsAXWG4cYIrlnrrEOKH6557HXsFp5IxeR3QvaKIoKGW1TJrMstpq+F4HRNHbhO7QOrtP/eu74HAkc68PFuhaFbq/5W42lTfhBQcxOvlc8fE6tad7lSp6oOkfLdk/WzJIOv/25qKDqYFoYqSKfKyWEHvlFUa1uR+i29Uu7nnVe/oZlfickj4yabe5jGQ6ghkLZ1i8jAjuO/kRLlcxqunAmQdNWiFIPys1kYpYbOtAAYPl3GrQlc6eCmnNu4Fzh0xiwzwosRxKtlRTVHvZ4g95VYwLGrYwuuBnhAMRNHM11qo7mKv9GeBTizgPOGDFMZSUiDuN1k9KQSIl/ZlQF1SOZVPvtd01aZhuXUw8azVIaFpAxF4iugIfAgUm05++CYtpcQHzCTSPmOjESWZDHHxjMDRQ4dzis8nF9ulJfvoEpNmh8k40iVlBETTDrXrdznu0dKYMOVncpVyLaRNR1/HoMNOFi9j9bgTsND5DOEdJ1Sjm3fXndDKSLm/DM2zNL5Gpg2tJKwTUiZHV73R9YdHApDwsgXnadfS1/MFuvRIMA8aGj3la5Eq70UUwXm9iqkuqZAbOVW2/rHA9S1IQoUKHiX75RvZgg8O9h8rZj1krornOTUUP67S1dJmn6H3qO/DDtN57d5T6Ze48Ltm9X7gWVJxWoTrYn7cHT2WRPY7QL6R5eum7gP9ympIs5
  template:
    metadata:
      name: gitlab-registry-secret
      namespace: task-app
    type: kubernetes.io/dockerconfigjson
