# Global settings
global:
  environment: development

# Frontend configuration
frontend:
  name: frontend
  replicas: 1
  apiUrl: "/api"
  image:
    repository: registry.gitlab.com/deeowemez/task-app/frontend
    tag: babe14cc
  service:
    type: ClusterIP
    port: 8080

# Backend configuration
backend:
  name: backend
  replicas: 1
  image:
    repository: registry.gitlab.com/deeowemez/task-app/backend
    tag: babe14cc
  service:
    type: ClusterIP
    port: 3000

# Database configuration
db:
  name: db
  replicas: 1
  db: taskdb
  username: postgres
  password: postgres
  image:
    repository: postgres
    tag: "15-alpine"

registrySecret:
  ewogICJhdXRocyI6IHsKICAgICJyZWdpc3RyeS5naXRsYWIuY29tIjogewogICAgICAidXNlcm5hbWUiOiAiZGVlb3dlbWV6IiwKICAgICAgInBhc3N3b3JkIjogImdscGF0LWw5NkVQM0RYNW10UmFMQlpMY1JIVW04Nk1RcDFPbXR5ZDNrd0N3LjAxLjEyMWtyenRsaiIsCiAgICAgICJhdXRoIjogIkJBU0U2NCh1c2VybmFtZTp0b2tlbikiCiAgICB9CiAgfQp9Cg==