apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      name: backend
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: app-backend:latest
        imagePullPolicy: Never
        ports: 
        - containerPort: 3000
          name: backend
        env:
        - name: NODE_ENV
          value: "development"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
        - name: POSTGRES_DB
          value: "taskdb"
        - name: POSTGRES_HOST
          value: "db"
        - name: POSTGRES_PORT
          value: "5432"
