# Global settings
global:
  environment: development

# Frontend configuration
frontend:
  name: frontend
  replicas: 1
  apiUrl: "/api"
  image:
    repository: registry.gitlab.com/deeowemez/task-app/frontend
    fe_tag: 7e42b50f
  service:
    type: ClusterIP
    port: 8080

# Backend configuration
backend:
  name: backend
  replicas: 1
  image:
    repository: registry.gitlab.com/deeowemez/task-app/backend
    be_tag: b4bc1704
  service:
    type: ClusterIP
    port: 3000

# Database configuration
db:
  name: db
  replicas: 1
  db: taskdb
  username: postgres
  password: postgres
  image:
    repository: postgres
    tag: "15-alpine"

